---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels: 
    name: mysql
spec: 
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      name: mysql
      labels:
        name: mysql
    spec:
      containers: 
        - resources:
            limits :
              cpu: 0.5
          image: mysql
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: yourpassword
          ports: 
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            path: /home/core/data/mysql
