---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
  name: redis
spec:
  containers:
  - name: redis
    image: redis:latest
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /data/redis
    ports: 
      - containerPort: 6379
        name: redis
  volumes:
  - name: redis-persistent-storage
    hostPath:
      path: /home/core/data/redis