---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    name: redis
  template:
    metadata:
      name: redis
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data/redis
        ports: 
          - containerPort: 6379
            name: redis
      volumes:
      - name: redis-persistent-storage
        hostPath:
          path: /home/core/data/redis